development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://oejygcufawpaer:a54f4e2f9c8f8d5862f375e1250cecc1a8fb670ba7434ec40f2005f6402217f6@ec2-54-225-118-55.compute-1.amazonaws.com:5432/d3tpvqqcesmgo

