# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c466e6a3f0b18d9536a14ffd74d72c5f5e24f41ff3c5c084f42f11d431fc94ab8fef0ed1ece7c6328be8790b0e2eea10482d95104afc769648c0ed94a4d225bf

test:
  secret_key_base: dc9597c847d41d0a095ef30369b4e9fee7809776388d99c036bb9e1b9f4def47b2c3eb724bece012c6d22ecfcb6ca9f006bc3b449fa3ff8ff6eef9e815a18075

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
